name: "transportation"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - selenium
      - db


  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # 開発用にローカルからもアクセス可能にする

volumes:
  db-data: