# PostgreSQL.
default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # これらの値はdocker-compose.ymlなどで環境変数として設定します
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: transportation_development

test:
  <<: *default
  database: transportation_test
  username: postgres
  password:
  host: localhost


production:
  <<: *default
  database: transportation_production
  # 本番環境ではよりセキュアな方法でパスワードを管理してください
  # password: <%= ENV["YOUR_APP_DATABASE_PASSWORD"] %>