# PostgreSQL.
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  # 環境変数からユーザー名を取得。CIでは"rails"、ローカルでは"postgres"を想定。
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: transportation_development

test:
  # CI/CD環境での接続エラーを確実に解消するため、値を直接指定します。
  # 継承や環境変数参照をなくし、設定の曖昧さを排除します。
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: transportation_test
  host: localhost
  username: rails
  password: password
  port: 5432

production:
  <<: *default
  database: transportation_production
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>