# PostgreSQL.
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  # usernameのデフォルト値を設定します。
  # これにより、意図しないユーザー名（例: root）での接続を防ぎます。
  username: <%= ENV.fetch("POSTGRES_USER", "rails") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: transportation_development
  # 開発環境用のユーザー名を明示的に指定
  username: <%= ENV.fetch("POSTGRES_USER", "vscode") %>

test:
  <<: *default
  database: transportation_test

production:
  <<: *default
  # 本番環境では DATABASE_URL 環境変数を使用するのが一般的です。
  # これにより、CI環境で不要な環境変数を探してエラーになることを防ぎます。
  url: <%= ENV["DATABASE_URL"] %>