# PostgreSQL.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # これらの値はdocker-compose.ymlやCIの環境変数として設定します
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  username: <%= ENV.fetch("PGUSER", "rails") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>

development:
  <<: *default
  database: transportation_development

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "transportation_test") %>

production:
  <<: *default
  database: transportation_production
  # 本番環境ではよりセキュアな方法でパスワードを管理してください
  # password: <%= ENV["YOUR_APP_DATABASE_PASSWORD"] %>